name: Auto Assign Priority

on:
  issues:
    types:
      - opened
      - edited

jobs:
  auto-priority:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Debug GITHUB_EVENT_NAME
        run: echo "Event: $GITHUB_EVENT_NAME"
      - name: Debug Issue Title
        run: echo "Issue Title: $issue_title"
      - name: Assign Priority Label
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "issues" ]]; then
            echo "Processing issue event..."
            if [[ "$issue_title" == *"SP: 3"* ]]; then
              echo "High priority detected."
              gh issue edit ${{ github.event.issue.number }} --add-label "Priority: High"
            elif [[ "$issue_title" == *"SP: 2"* ]]; then
              echo "Medium priority detected."
              gh issue edit ${{ github.event.issue.number }} --add-label "Priority: Medium"
            elif [[ "$issue_title" == *"SP: 1"* ]]; then
              echo "Low priority detected."
              gh issue edit ${{ github.event.issue.number }} --add-label "Priority: Low"
            else
              echo "No matching priority found."
            fi
          else
            echo "Not an issue event."
          fi
