name: Generate Changelog from PRs

on:
  pull_request:
    types: [closed]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract PR Title
        run: |
          echo "- ${{ github.event.pull_request.title }}" >> changelog_update.txt

      - name: Append to Changelog
        run: |
          echo "## [Unreleased]" > temp_changelog.txt
          cat changelog_update.txt >> temp_changelog.txt
          cat CHANGELOG.md >> temp_changelog.txt
          mv temp_changelog.txt CHANGELOG.md

      - name: Commit Updated Changelog
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG"
          git push
